version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
